version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:               
      - "./var:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - default     

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
        - db
    environment:
      PMA_HOST: db  
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password     
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    ports:
      - "8081:80"
      - "8443:443"
    depends_on:
      - db
    networks:
      - default     

  www:
      build: .
      container_name : WebUnow
      restart: always
      ports: 
            - "8080:80"
      volumes:
            - ./html:/var/www/html
      networks:
            - default        

volumes:
  db_data:
