nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Cambia esto por los orígenes específicos si es necesario
        allow_headers: ['Authorization', 'Content-Type', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~